### ISSUE TITLE
No SMG-multimodal-grasping/code/objects/training/grasping_suitable bug

### ISSUE THREAD

**Issue by Zhaocka** [fukangl/SMG-multimodal-grasping#1]
Thank you very much for your meaningful work.  I want to repeat your work according to your instructions written in the readme.md. 

I created a virtual environment using conda. And I have installed all dependent packages metioned in the readme.md. When I run the `python main.py --is_sim --method 'reinforcement' --is_ets --is_pe --is_oo --explore_rate_decay`, I first met 
- File "main.py", line 431, in <module>
    parser.add_argument('--is_sim', dest='is_sim', action='store_true', default=False,                                      help='run in simulation?')
NameError: name 'parser' is not defined`

and I add `parser = argparse.ArgumentParser()` in the main.py. After I add this, I met this problem

- No such file or directory: SMG-multimodal-grasping/code/objects/training/grasping_suitable'

So I want to know if a part of the dataset missing.

**Comment by fukangl** [comment]
Hi,

Thanks for reaching out and your interest in my work. Sorry for the dataset
error. I will work on resolving this issue and get back to you as soon as
possible. Thank you!

Best,
Fukang

**Comment by fukangl** [comment]
We have resolved this issue. Let me know if you have any questions. Thank
you!
