### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by Gwen-JW** [fukangl/SMG-multimodal-grasping#2]
Thank you for your great work!

I am trying to create a virtual environment according to your README, can I ask your PyTorch and python version that you used? Because I met some issues when I tried to install apex. Thank you!

**Comment by fukangl** [comment]
Thank you for your interest in our work! Our project was developed using
Python3 and PyTorch 1.5.1. Please note that PyTorch 1.0 or later is
required to run our code.

**Comment by Gwen-JW** [comment]
Thanks, already fixed the problem.
