### ISSUE TITLE
On dataset

### ISSUE THREAD

**Issue by yyf17** [fukangl/SMG-multimodal-grasping#3]
Very nice work. The file datasets.zip of the dataset I downloaded is very small, only 134B. Can you provide the dataset through the network disk?

**Comment by fukangl** [comment]
Thank you for your interest in our work. Please download the dataset
through this link:
https://github.com/fukangl/SMG-multimodal-grasping/blob/main/datasets.zip
If you encounter any issues, please let us know.

**Comment by yyf17** [comment]
@fukangl Thank you!
